server:
  address: 0.0.0.0
  port: 9678
spring:
  thymeleaf:
    cache: false
  application:
    name: woodwhales-media
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/woodwhales-media?serverTimezone=Asia/Shanghai&useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
logging:
  level:
    cn.woodwhales.media: debug
  file:
    path: /data/woodwhales-media/